/*
    Overview:
    This query analyzes job postings to count the occurrence of specific technical skills and skill types for each distinct job title.
    It joins job postings with their associated skills, then aggregates counts for each skill (as columns prefixed with 'skill_') and each skill type (as columns prefixed with 'type_').
    The result provides a detailed breakdown of which skills and skill categories are most frequently required for each job title, supporting skill demand analysis and workforce planning.
*/


-- SELECT DISTINCT skills
-- FROM skills_dim;

-- SELECT DISTINCT type
-- FROM skills_dim;
 

-- SELECT job_postings_fact.job_title_short AS job_title,
--     skills_dim.skills  AS skills ,
--     skills_dim.type AS type

-- FROM job_postings_fact
--     INNER JOIN skills_job_dim ON job_postings_fact.job_id = skills_job_dim.job_id
--     INNER JOIN skills_dim ON skills_job_dim.skill_id = skills_dim.skill_id
-- GROUP BY job_postings_fact.job_title_short,
--     skills_dim.skills,
--     skills_dim.type;
    
SELECT 
    job_postings_fact.job_title_short AS job_title,
    
    -- Skills counts
    COUNT(CASE WHEN skills_dim.skills = 'rocketchat' THEN 1 END) AS rocketchat_count,
    COUNT(CASE WHEN skills_dim.skills = 'wire' THEN 1 END) AS wire_count,
    COUNT(CASE WHEN skills_dim.skills = 'clickup' THEN 1 END) AS clickup_count,
    COUNT(CASE WHEN skills_dim.skills = 'gitlab' THEN 1 END) AS gitlab_count,
    COUNT(CASE WHEN skills_dim.skills = 'powerbi' THEN 1 END) AS powerbi_count,
    COUNT(CASE WHEN skills_dim.skills = 'bitbucket' THEN 1 END) AS bitbucket_count,
    COUNT(CASE WHEN skills_dim.skills = 'python' THEN 1 END) AS python_count,
    COUNT(CASE WHEN skills_dim.skills = 'vue' THEN 1 END) AS vue_count,
    COUNT(CASE WHEN skills_dim.skills = 'svn' THEN 1 END) AS svn_count,
    COUNT(CASE WHEN skills_dim.skills = 'nuix' THEN 1 END) AS nuix_count,
    COUNT(CASE WHEN skills_dim.skills = 'sql server' THEN 1 END) AS sql_server_count,
    COUNT(CASE WHEN skills_dim.skills = 'plotly' THEN 1 END) AS plotly_count,
    COUNT(CASE WHEN skills_dim.skills = 'f#' THEN 1 END) AS f_sharp_count,
    COUNT(CASE WHEN skills_dim.skills = 'jquery' THEN 1 END) AS jquery_count,
    COUNT(CASE WHEN skills_dim.skills = 'linode' THEN 1 END) AS linode_count,
    COUNT(CASE WHEN skills_dim.skills = 'shell' THEN 1 END) AS shell_count,
    COUNT(CASE WHEN skills_dim.skills = 'couchbase' THEN 1 END) AS couchbase_count,
    COUNT(CASE WHEN skills_dim.skills = 'xamarin' THEN 1 END) AS xamarin_count,
    COUNT(CASE WHEN skills_dim.skills = 'react' THEN 1 END) AS react_count,
    COUNT(CASE WHEN skills_dim.skills = 'mlr' THEN 1 END) AS mlr_count,
    COUNT(CASE WHEN skills_dim.skills = 'drupal' THEN 1 END) AS drupal_count,
    COUNT(CASE WHEN skills_dim.skills = 'firestore' THEN 1 END) AS firestore_count,
    COUNT(CASE WHEN skills_dim.skills = 'opencv' THEN 1 END) AS opencv_count,
    COUNT(CASE WHEN skills_dim.skills = 'go' THEN 1 END) AS go_count,
    COUNT(CASE WHEN skills_dim.skills = 'tableau' THEN 1 END) AS tableau_count,
    COUNT(CASE WHEN skills_dim.skills = 'ansible' THEN 1 END) AS ansible_count,
    COUNT(CASE WHEN skills_dim.skills = 'java' THEN 1 END) AS java_count,
    COUNT(CASE WHEN skills_dim.skills = 'unreal' THEN 1 END) AS unreal_count,
    COUNT(CASE WHEN skills_dim.skills = 'dingtalk' THEN 1 END) AS dingtalk_count,
    COUNT(CASE WHEN skills_dim.skills = 'codecommit' THEN 1 END) AS codecommit_count,
    COUNT(CASE WHEN skills_dim.skills = 'ember.js' THEN 1 END) AS ember_js_count,
    COUNT(CASE WHEN skills_dim.skills = 'react.js' THEN 1 END) AS react_js_count,
    COUNT(CASE WHEN skills_dim.skills = 'typescript' THEN 1 END) AS typescript_count,
    COUNT(CASE WHEN skills_dim.skills = 'slack' THEN 1 END) AS slack_count,
    COUNT(CASE WHEN skills_dim.skills = 'scikit-learn' THEN 1 END) AS scikit_learn_count,
    COUNT(CASE WHEN skills_dim.skills = 'c++' THEN 1 END) AS cpp_count,
    COUNT(CASE WHEN skills_dim.skills = 'flask' THEN 1 END) AS flask_count,
    COUNT(CASE WHEN skills_dim.skills = 'postgresql' THEN 1 END) AS postgresql_count,
    COUNT(CASE WHEN skills_dim.skills = 'visio' THEN 1 END) AS visio_count,
    COUNT(CASE WHEN skills_dim.skills = 'clojure' THEN 1 END) AS clojure_count,
    COUNT(CASE WHEN skills_dim.skills = 'gtx' THEN 1 END) AS gtx_count,
    COUNT(CASE WHEN skills_dim.skills = 'html' THEN 1 END) AS html_count,
    COUNT(CASE WHEN skills_dim.skills = 'outlook' THEN 1 END) AS outlook_count,
    COUNT(CASE WHEN skills_dim.skills = 'yarn' THEN 1 END) AS yarn_count,
    COUNT(CASE WHEN skills_dim.skills = 'node' THEN 1 END) AS node_count,
    COUNT(CASE WHEN skills_dim.skills = 'asana' THEN 1 END) AS asana_count,
    COUNT(CASE WHEN skills_dim.skills = 'mxnet' THEN 1 END) AS mxnet_count,
    COUNT(CASE WHEN skills_dim.skills = 'unity' THEN 1 END) AS unity_count,
    COUNT(CASE WHEN skills_dim.skills = 'angular' THEN 1 END) AS angular_count,
    COUNT(CASE WHEN skills_dim.skills = 'pytorch' THEN 1 END) AS pytorch_count,
    COUNT(CASE WHEN skills_dim.skills = 'ringcentral' THEN 1 END) AS ringcentral_count,
    COUNT(CASE WHEN skills_dim.skills = 'ovh' THEN 1 END) AS ovh_count,
    COUNT(CASE WHEN skills_dim.skills = 'deno' THEN 1 END) AS deno_count,
    COUNT(CASE WHEN skills_dim.skills = 'datarobot' THEN 1 END) AS datarobot_count,
    COUNT(CASE WHEN skills_dim.skills = 'blazor' THEN 1 END) AS blazor_count,
    COUNT(CASE WHEN skills_dim.skills = 'spark' THEN 1 END) AS spark_count,
    COUNT(CASE WHEN skills_dim.skills = 'cobol' THEN 1 END) AS cobol_count,
    COUNT(CASE WHEN skills_dim.skills = 'julia' THEN 1 END) AS julia_count,
    COUNT(CASE WHEN skills_dim.skills = 'laravel' THEN 1 END) AS laravel_count,
    COUNT(CASE WHEN skills_dim.skills = 'suse' THEN 1 END) AS suse_count,
    COUNT(CASE WHEN skills_dim.skills = 'ubuntu' THEN 1 END) AS ubuntu_count,
    COUNT(CASE WHEN skills_dim.skills = 'play framework' THEN 1 END) AS play_framework_count,
    COUNT(CASE WHEN skills_dim.skills = 'word' THEN 1 END) AS word_count,
    COUNT(CASE WHEN skills_dim.skills = 'rshiny' THEN 1 END) AS rshiny_count,
    COUNT(CASE WHEN skills_dim.skills = 'power bi' THEN 1 END) AS power_bi_count,
    COUNT(CASE WHEN skills_dim.skills = 'bash' THEN 1 END) AS bash_count,
    COUNT(CASE WHEN skills_dim.skills = 'atlassian' THEN 1 END) AS atlassian_count,
    COUNT(CASE WHEN skills_dim.skills = 'spreadsheet' THEN 1 END) AS spreadsheet_count,
    COUNT(CASE WHEN skills_dim.skills = 'powerpoint' THEN 1 END) AS powerpoint_count,
    COUNT(CASE WHEN skills_dim.skills = 'mlpack' THEN 1 END) AS mlpack_count,
    COUNT(CASE WHEN skills_dim.skills = 'oracle' THEN 1 END) AS oracle_count,
    COUNT(CASE WHEN skills_dim.skills = 'chainer' THEN 1 END) AS chainer_count,
    COUNT(CASE WHEN skills_dim.skills = 'asp.net' THEN 1 END) AS asp_net_count,
    COUNT(CASE WHEN skills_dim.skills = 'css' THEN 1 END) AS css_count,
    COUNT(CASE WHEN skills_dim.skills = 'delphi' THEN 1 END) AS delphi_count,
    COUNT(CASE WHEN skills_dim.skills = 'kali' THEN 1 END) AS kali_count,
    COUNT(CASE WHEN skills_dim.skills = 'ibm cloud' THEN 1 END) AS ibm_cloud_count,
    COUNT(CASE WHEN skills_dim.skills = 'bigquery' THEN 1 END) AS bigquery_count,
    COUNT(CASE WHEN skills_dim.skills = 'trello' THEN 1 END) AS trello_count,
    COUNT(CASE WHEN skills_dim.skills = 'solidity' THEN 1 END) AS solidity_count,
    COUNT(CASE WHEN skills_dim.skills = 'pandas' THEN 1 END) AS pandas_count,
    COUNT(CASE WHEN skills_dim.skills = 'npm' THEN 1 END) AS npm_count,
    COUNT(CASE WHEN skills_dim.skills = 'alteryx' THEN 1 END) AS alteryx_count,
    COUNT(CASE WHEN skills_dim.skills = 'gdpr' THEN 1 END) AS gdpr_count,
    COUNT(CASE WHEN skills_dim.skills = 'assembly' THEN 1 END) AS assembly_count,
    COUNT(CASE WHEN skills_dim.skills = 'mattermost' THEN 1 END) AS mattermost_count,
    COUNT(CASE WHEN skills_dim.skills = 'microstrategy' THEN 1 END) AS microstrategy_count,
    COUNT(CASE WHEN skills_dim.skills = 'homebrew' THEN 1 END) AS homebrew_count,
    COUNT(CASE WHEN skills_dim.skills = 'wimi' THEN 1 END) AS wimi_count,
    COUNT(CASE WHEN skills_dim.skills = 'rust' THEN 1 END) AS rust_count,
    COUNT(CASE WHEN skills_dim.skills = 'mongodb' THEN 1 END) AS mongodb_count,
    COUNT(CASE WHEN skills_dim.skills = 'esquisse' THEN 1 END) AS esquisse_count,
    COUNT(CASE WHEN skills_dim.skills = 'redhat' THEN 1 END) AS redhat_count,
    COUNT(CASE WHEN skills_dim.skills = 'ssrs' THEN 1 END) AS ssrs_count,
    COUNT(CASE WHEN skills_dim.skills = 'kafka' THEN 1 END) AS kafka_count,
    COUNT(CASE WHEN skills_dim.skills = 'windows' THEN 1 END) AS windows_count,
    COUNT(CASE WHEN skills_dim.skills = 'huggingface' THEN 1 END) AS huggingface_count,
    COUNT(CASE WHEN skills_dim.skills = 'theano' THEN 1 END) AS theano_count,
    COUNT(CASE WHEN skills_dim.skills = 'vmware' THEN 1 END) AS vmware_count,
    COUNT(CASE WHEN skills_dim.skills = 'nosql' THEN 1 END) AS nosql_count,
    COUNT(CASE WHEN skills_dim.skills = 'ionic' THEN 1 END) AS ionic_count,
    COUNT(CASE WHEN skills_dim.skills = 'sheets' THEN 1 END) AS sheets_count,
    COUNT(CASE WHEN skills_dim.skills = 'symfony' THEN 1 END) AS symfony_count,
    COUNT(CASE WHEN skills_dim.skills = 'visualbasic' THEN 1 END) AS visualbasic_count,
    COUNT(CASE WHEN skills_dim.skills = 'mysql' THEN 1 END) AS mysql_count,
    COUNT(CASE WHEN skills_dim.skills = 'node.js' THEN 1 END) AS node_js_count,
    COUNT(CASE WHEN skills_dim.skills = 't-sql' THEN 1 END) AS t_sql_count,
    COUNT(CASE WHEN skills_dim.skills = 'monday.com' THEN 1 END) AS monday_com_count,
    COUNT(CASE WHEN skills_dim.skills = 'elixir' THEN 1 END) AS elixir_count,
    COUNT(CASE WHEN skills_dim.skills = 'flow' THEN 1 END) AS flow_count,
    COUNT(CASE WHEN skills_dim.skills = 'fastify' THEN 1 END) AS fastify_count,
    COUNT(CASE WHEN skills_dim.skills = 'sqlite' THEN 1 END) AS sqlite_count,
    COUNT(CASE WHEN skills_dim.skills = 'powershell' THEN 1 END) AS powershell_count,
    COUNT(CASE WHEN skills_dim.skills = 'gcp' THEN 1 END) AS gcp_count,
    COUNT(CASE WHEN skills_dim.skills = 'linux' THEN 1 END) AS linux_count,
    COUNT(CASE WHEN skills_dim.skills = 'aurora' THEN 1 END) AS aurora_count,
    COUNT(CASE WHEN skills_dim.skills = 'jenkins' THEN 1 END) AS jenkins_count,
    COUNT(CASE WHEN skills_dim.skills = 'qt' THEN 1 END) AS qt_count,
    COUNT(CASE WHEN skills_dim.skills = 'elasticsearch' THEN 1 END) AS elasticsearch_count,
    COUNT(CASE WHEN skills_dim.skills = 'asp.net core' THEN 1 END) AS asp_net_core_count,
    COUNT(CASE WHEN skills_dim.skills = 'macos' THEN 1 END) AS macos_count,
    COUNT(CASE WHEN skills_dim.skills = 'groovy' THEN 1 END) AS groovy_count,
    COUNT(CASE WHEN skills_dim.skills = 'microsoft teams' THEN 1 END) AS microsoft_teams_count,
    COUNT(CASE WHEN skills_dim.skills = 'sap' THEN 1 END) AS sap_count,
    COUNT(CASE WHEN skills_dim.skills = 'jupyter' THEN 1 END) AS jupyter_count,
    COUNT(CASE WHEN skills_dim.skills = 'watson' THEN 1 END) AS watson_count,
    COUNT(CASE WHEN skills_dim.skills = 'haskell' THEN 1 END) AS haskell_count,
    COUNT(CASE WHEN skills_dim.skills = 'tidyr' THEN 1 END) AS tidyr_count,
    COUNT(CASE WHEN skills_dim.skills = 'r' THEN 1 END) AS r_count,
    COUNT(CASE WHEN skills_dim.skills = 'digitalocean' THEN 1 END) AS digitalocean_count,
    COUNT(CASE WHEN skills_dim.skills = 'no-sql' THEN 1 END) AS no_sql_count,
    COUNT(CASE WHEN skills_dim.skills = 'zoom' THEN 1 END) AS zoom_count,
    COUNT(CASE WHEN skills_dim.skills = 'flutter' THEN 1 END) AS flutter_count,
    COUNT(CASE WHEN skills_dim.skills = 'lua' THEN 1 END) AS lua_count,
    COUNT(CASE WHEN skills_dim.skills = 'airtable' THEN 1 END) AS airtable_count,
    COUNT(CASE WHEN skills_dim.skills = 'confluence' THEN 1 END) AS confluence_count,
    COUNT(CASE WHEN skills_dim.skills = 'dplyr' THEN 1 END) AS dplyr_count,
    COUNT(CASE WHEN skills_dim.skills = 'chef' THEN 1 END) AS chef_count,
    COUNT(CASE WHEN skills_dim.skills = 'dlib' THEN 1 END) AS dlib_count,
    COUNT(CASE WHEN skills_dim.skills = 'nltk' THEN 1 END) AS nltk_count,
    COUNT(CASE WHEN skills_dim.skills = 'webex' THEN 1 END) AS webex_count,
    COUNT(CASE WHEN skills_dim.skills = 'wrike' THEN 1 END) AS wrike_count,
    COUNT(CASE WHEN skills_dim.skills = 'unix' THEN 1 END) AS unix_count,
    COUNT(CASE WHEN skills_dim.skills = 'couchdb' THEN 1 END) AS couchdb_count,
    COUNT(CASE WHEN skills_dim.skills = 'aws' THEN 1 END) AS aws_count,
    COUNT(CASE WHEN skills_dim.skills = 'wsl' THEN 1 END) AS wsl_count,
    COUNT(CASE WHEN skills_dim.skills = 'excel' THEN 1 END) AS excel_count,
    COUNT(CASE WHEN skills_dim.skills = 'php' THEN 1 END) AS php_count,
    COUNT(CASE WHEN skills_dim.skills = 'puppet' THEN 1 END) AS puppet_count,
    COUNT(CASE WHEN skills_dim.skills = 'neo4j' THEN 1 END) AS neo4j_count,
    COUNT(CASE WHEN skills_dim.skills = 'firebase' THEN 1 END) AS firebase_count,
    COUNT(CASE WHEN skills_dim.skills = 'notion' THEN 1 END) AS notion_count,
    COUNT(CASE WHEN skills_dim.skills = 'crystal' THEN 1 END) AS crystal_count,
    COUNT(CASE WHEN skills_dim.skills = 'airflow' THEN 1 END) AS airflow_count,
    COUNT(CASE WHEN skills_dim.skills = 'tensorflow' THEN 1 END) AS tensorflow_count,
    COUNT(CASE WHEN skills_dim.skills = 'kotlin' THEN 1 END) AS kotlin_count,
    COUNT(CASE WHEN skills_dim.skills = 'c#' THEN 1 END) AS c_sharp_count,
    COUNT(CASE WHEN skills_dim.skills = 'colocation' THEN 1 END) AS colocation_count,
    COUNT(CASE WHEN skills_dim.skills = 'splunk' THEN 1 END) AS splunk_count,
    COUNT(CASE WHEN skills_dim.skills = 'apl' THEN 1 END) AS apl_count,
    COUNT(CASE WHEN skills_dim.skills = 'hugging face' THEN 1 END) AS hugging_face_count,
    COUNT(CASE WHEN skills_dim.skills = 'keras' THEN 1 END) AS keras_count,
    COUNT(CASE WHEN skills_dim.skills = 'ssis' THEN 1 END) AS ssis_count,
    COUNT(CASE WHEN skills_dim.skills = 'heroku' THEN 1 END) AS heroku_count,
    COUNT(CASE WHEN skills_dim.skills = 'twilio' THEN 1 END) AS twilio_count,
    COUNT(CASE WHEN skills_dim.skills = 'tidyverse' THEN 1 END) AS tidyverse_count,
    COUNT(CASE WHEN skills_dim.skills = 'fedora' THEN 1 END) AS fedora_count,
    COUNT(CASE WHEN skills_dim.skills = 'express' THEN 1 END) AS express_count,
    COUNT(CASE WHEN skills_dim.skills = 'django' THEN 1 END) AS django_count,
    COUNT(CASE WHEN skills_dim.skills = 'ruby' THEN 1 END) AS ruby_count,
    COUNT(CASE WHEN skills_dim.skills = 'debian' THEN 1 END) AS debian_count,
    COUNT(CASE WHEN skills_dim.skills = 'seaborn' THEN 1 END) AS seaborn_count,
    COUNT(CASE WHEN skills_dim.skills = 'vb.net' THEN 1 END) AS vb_net_count,
    COUNT(CASE WHEN skills_dim.skills = 'javascript' THEN 1 END) AS javascript_count,
    COUNT(CASE WHEN skills_dim.skills = 'rubyon rails' THEN 1 END) AS rubyon_rails_count,
    COUNT(CASE WHEN skills_dim.skills = 'sqlserver' THEN 1 END) AS sqlserver_count,
    COUNT(CASE WHEN skills_dim.skills = 'jira' THEN 1 END) AS jira_count,
    COUNT(CASE WHEN skills_dim.skills = 'graphql' THEN 1 END) AS graphql_count,
    COUNT(CASE WHEN skills_dim.skills = 'dax' THEN 1 END) AS dax_count,
    COUNT(CASE WHEN skills_dim.skills = 'redis' THEN 1 END) AS redis_count,
    COUNT(CASE WHEN skills_dim.skills = 'msaccess' THEN 1 END) AS msaccess_count,
    COUNT(CASE WHEN skills_dim.skills = 'fastapi' THEN 1 END) AS fastapi_count,
    COUNT(CASE WHEN skills_dim.skills = 'objective-c' THEN 1 END) AS objective_c_count,
    COUNT(CASE WHEN skills_dim.skills = 'visual basic' THEN 1 END) AS visual_basic_count,
    COUNT(CASE WHEN skills_dim.skills = 'ruby on rails' THEN 1 END) AS ruby_on_rails_count,
    COUNT(CASE WHEN skills_dim.skills = 'terraform' THEN 1 END) AS terraform_count,
    COUNT(CASE WHEN skills_dim.skills = 'ggplot2' THEN 1 END) AS ggplot2_count,
    COUNT(CASE WHEN skills_dim.skills = 'docker' THEN 1 END) AS docker_count,
    COUNT(CASE WHEN skills_dim.skills = 'swift' THEN 1 END) AS swift_count,
    COUNT(CASE WHEN skills_dim.skills = 'electron' THEN 1 END) AS electron_count,
    COUNT(CASE WHEN skills_dim.skills = 'cassandra' THEN 1 END) AS cassandra_count,
    COUNT(CASE WHEN skills_dim.skills = 'pascal' THEN 1 END) AS pascal_count,
    COUNT(CASE WHEN skills_dim.skills = 'erlang' THEN 1 END) AS erlang_count,
    COUNT(CASE WHEN skills_dim.skills = 'next.js' THEN 1 END) AS next_js_count,
    COUNT(CASE WHEN skills_dim.skills = 'pulumi' THEN 1 END) AS pulumi_count,
    COUNT(CASE WHEN skills_dim.skills = 'dynamodb' THEN 1 END) AS dynamodb_count,
    COUNT(CASE WHEN skills_dim.skills = 'svelte' THEN 1 END) AS svelte_count,
    COUNT(CASE WHEN skills_dim.skills = 'cordova' THEN 1 END) AS cordova_count,
    COUNT(CASE WHEN skills_dim.skills = 'arch' THEN 1 END) AS arch_count,
    COUNT(CASE WHEN skills_dim.skills = 'github' THEN 1 END) AS github_count,
    COUNT(CASE WHEN skills_dim.skills = 'microsoft lists' THEN 1 END) AS microsoft_lists_count,
    COUNT(CASE WHEN skills_dim.skills = 'c' THEN 1 END) AS c_count,
    COUNT(CASE WHEN skills_dim.skills = 'angular.js' THEN 1 END) AS angular_js_count,
    COUNT(CASE WHEN skills_dim.skills = 'pyspark' THEN 1 END) AS pyspark_count,
    COUNT(CASE WHEN skills_dim.skills = 'git' THEN 1 END) AS git_count,
    COUNT(CASE WHEN skills_dim.skills = 'numpy' THEN 1 END) AS numpy_count,
    COUNT(CASE WHEN skills_dim.skills = 'gatsby' THEN 1 END) AS gatsby_count,
    COUNT(CASE WHEN skills_dim.skills = 'lisp' THEN 1 END) AS lisp_count,
    COUNT(CASE WHEN skills_dim.skills = 'cognos' THEN 1 END) AS cognos_count,
    COUNT(CASE WHEN skills_dim.skills = 'workfront' THEN 1 END) AS workfront_count,
    COUNT(CASE WHEN skills_dim.skills = 'planner' THEN 1 END) AS planner_count,
    COUNT(CASE WHEN skills_dim.skills = 'sass' THEN 1 END) AS sass_count,
    COUNT(CASE WHEN skills_dim.skills = 'redshift' THEN 1 END) AS redshift_count,
    COUNT(CASE WHEN skills_dim.skills = 'kubernetes' THEN 1 END) AS kubernetes_count,
    COUNT(CASE WHEN skills_dim.skills = 'perl' THEN 1 END) AS perl_count,
    COUNT(CASE WHEN skills_dim.skills = 'asp.netcore' THEN 1 END) AS asp_netcore_count,
    COUNT(CASE WHEN skills_dim.skills = 'openstack' THEN 1 END) AS openstack_count,
    COUNT(CASE WHEN skills_dim.skills = 'centos' THEN 1 END) AS centos_count,
    COUNT(CASE WHEN skills_dim.skills = 'fortran' THEN 1 END) AS fortran_count,
    COUNT(CASE WHEN skills_dim.skills = 'snowflake' THEN 1 END) AS snowflake_count,
    COUNT(CASE WHEN skills_dim.skills = 'azure' THEN 1 END) AS azure_count,
    COUNT(CASE WHEN skills_dim.skills = 'ocaml' THEN 1 END) AS ocaml_count,
    COUNT(CASE WHEN skills_dim.skills = 'smartsheet' THEN 1 END) AS smartsheet_count,
    COUNT(CASE WHEN skills_dim.skills = 'db2' THEN 1 END) AS db2_count,
    COUNT(CASE WHEN skills_dim.skills = 'mongo' THEN 1 END) AS mongo_count,
    COUNT(CASE WHEN skills_dim.skills = 'selenium' THEN 1 END) AS selenium_count,
    COUNT(CASE WHEN skills_dim.skills = 'unify' THEN 1 END) AS unify_count,
    COUNT(CASE WHEN skills_dim.skills = 'databricks' THEN 1 END) AS databricks_count,
    COUNT(CASE WHEN skills_dim.skills = 'terminal' THEN 1 END) AS terminal_count,
    COUNT(CASE WHEN skills_dim.skills = 'spring' THEN 1 END) AS spring_count,
    COUNT(CASE WHEN skills_dim.skills = 'mariadb' THEN 1 END) AS mariadb_count,
    COUNT(CASE WHEN skills_dim.skills = 'spss' THEN 1 END) AS spss_count,
    COUNT(CASE WHEN skills_dim.skills = 'symphony' THEN 1 END) AS symphony_count,
    COUNT(CASE WHEN skills_dim.skills = 'vba' THEN 1 END) AS vba_count,
    COUNT(CASE WHEN skills_dim.skills = 'scala' THEN 1 END) AS scala_count,
    COUNT(CASE WHEN skills_dim.skills = 'sql' THEN 1 END) AS sql_count,
    COUNT(CASE WHEN skills_dim.skills = 'qlik' THEN 1 END) AS qlik_count,
    COUNT(CASE WHEN skills_dim.skills = 'vue.js' THEN 1 END) AS vue_js_count,
    COUNT(CASE WHEN skills_dim.skills = 'ms access' THEN 1 END) AS ms_access_count,
    COUNT(CASE WHEN skills_dim.skills = 'golang' THEN 1 END) AS golang_count,
    COUNT(CASE WHEN skills_dim.skills = 'sharepoint' THEN 1 END) AS sharepoint_count,
    COUNT(CASE WHEN skills_dim.skills = 'nuxt.js' THEN 1 END) AS nuxt_js_count,
    COUNT(CASE WHEN skills_dim.skills = 'capacitor' THEN 1 END) AS capacitor_count,
    COUNT(CASE WHEN skills_dim.skills = 'shogun' THEN 1 END) AS shogun_count,
    COUNT(CASE WHEN skills_dim.skills = 'phoenix' THEN 1 END) AS phoenix_count,
    COUNT(CASE WHEN skills_dim.skills = 'dart' THEN 1 END) AS dart_count,
    COUNT(CASE WHEN skills_dim.skills = 'google chat' THEN 1 END) AS google_chat_count,
    COUNT(CASE WHEN skills_dim.skills = 'hadoop' THEN 1 END) AS hadoop_count,
    COUNT(CASE WHEN skills_dim.skills = 'sas' THEN 1 END) AS sas_count,
    COUNT(CASE WHEN skills_dim.skills = 'looker' THEN 1 END) AS looker_count,
    COUNT(CASE WHEN skills_dim.skills = 'matplotlib' THEN 1 END) AS matplotlib_count,
    COUNT(CASE WHEN skills_dim.skills = 'matlab' THEN 1 END) AS matlab_count

FROM job_postings_fact
    INNER JOIN skills_job_dim ON job_postings_fact.job_id = skills_job_dim.job_id
    INNER JOIN skills_dim ON skills_job_dim.skill_id = skills_dim.skill_id
GROUP BY job_postings_fact.job_title_short
ORDER BY job_postings_fact.job_title_short;



SELECT 
    job_postings_fact.job_title_short AS job_title,
    
    -- Type counts
    COUNT(CASE WHEN skills_dim.type = 'programming' THEN 1 END) AS programming_count,
    COUNT(CASE WHEN skills_dim.type = 'sync' THEN 1 END) AS sync_count,
    COUNT(CASE WHEN skills_dim.type = 'analyst_tools' THEN 1 END) AS analyst_tools_count,
    COUNT(CASE WHEN skills_dim.type = 'libraries' THEN 1 END) AS libraries_count,
    COUNT(CASE WHEN skills_dim.type = 'databases' THEN 1 END) AS databases_count,
    COUNT(CASE WHEN skills_dim.type = 'webframeworks' THEN 1 END) AS webframeworks_count,
    COUNT(CASE WHEN skills_dim.type = 'os' THEN 1 END) AS os_count,
    COUNT(CASE WHEN skills_dim.type = 'cloud' THEN 1 END) AS cloud_count,
    COUNT(CASE WHEN skills_dim.type = 'other' THEN 1 END) AS other_count,
    COUNT(CASE WHEN skills_dim.type = 'async' THEN 1 END) AS async_count

FROM job_postings_fact
    INNER JOIN skills_job_dim ON job_postings_fact.job_id = skills_job_dim.job_id
    INNER JOIN skills_dim ON skills_job_dim.skill_id = skills_dim.skill_id
GROUP BY job_postings_fact.job_title_short
ORDER BY job_postings_fact.job_title_short;

